# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lecture.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import video_pb2 as video__pb2
import article_pb2 as article__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlecture.proto\x1a\x0bvideo.proto\x1a\rarticle.proto\"J\n\x07Lecture\x12\x17\n\x05video\x18\x01 \x01(\x0b\x32\x06.VideoH\x00\x12\x1b\n\x07\x61rticle\x18\x02 \x01(\x0b\x32\x08.ArticleH\x00\x42\t\n\x07\x63ontentb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lecture_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LECTURE._serialized_start=45
  _LECTURE._serialized_end=119
# @@protoc_insertion_point(module_scope)
