# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\"]\n\x05Video\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.Video.VideoType\x12\x0b\n\x03url\x18\x02 \x01(\t\"\'\n\tVideoType\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03MP4\x10\x01\x12\x07\n\x03MOV\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEO._serialized_start=15
  _VIDEO._serialized_end=108
  _VIDEO_VIDEOTYPE._serialized_start=69
  _VIDEO_VIDEOTYPE._serialized_end=108
# @@protoc_insertion_point(module_scope)
